/**
 * Seed script pro vložení 1000 slov do tabulky `words`.
 * Spusť s ts-node: `ts-node scripts/seed.ts`
 *
 * Vyžaduje SUPABASE_SERVICE_ROLE_KEY v .env
 */
import { supabaseServer } from '../lib/supabaseServer';

const words: string[] = [
  // 1000 jednoduchých českých slov vhodných pro 15let
  // (seznam níže)
  "pes","kočka","auto","dům","stůl","židle","kolo","škola","učitel","žák",
  "kniha","pero","tužka","okno","dveře","park","strom","květina","kopec","řeka",
  "jezero","les","tráva","slunce","měsíc","hvězda","nebe","mrak","déšť","sníh",
  "vítr","bouřka","sladké","sůl","chléb","sýr","jablko","hruška","banán","pomeranč",
  "voda","čaj","káva","mléko","džus","polévka","hovězí","kuře","ryba","brambory",
  "rýže","těstoviny","salát","máslo","olej","cukr","sušenka","dezert","koláč","torta",
  "boty","tričko","kalhoty","svetr","bunda","čepice","rukavice","ponožky","šaty","sukně",
  "brýle","hodinky","peněženka","klíč","telefon","počítač","notebook","televize","rádio","sluchátka",
  "fotka","kamera","film","hudba","píseň","tanec","sport","fotbal","basketbal","plavání",
  "běh","cyklistika","lyže","hokej","tenis","raketa","míč","cvičení","tým","zápas",
  "hra","karta","kostka","puzzle","hračka","panenka","robot","stavebnice","malování","kresba",
  "barva","červená","modrá","zelená","žlutá","černá","bílá","šedá","oranžová","fialová",
  "rodina","matka","otec","bratr","sestra","babička","dědeček","soused","kamarád","přítel",
  "láska","smích","radost","smutek","strach","rozum","mysl","nápad","plán","cíl",
  "čas","den","noc","ranní","odpoledne","večer","víkend","prázdniny","práce","úkol",
  "test","zkouška","známka","domácí úkol","učebnice","laboratoř","třída","lavice","tabule","kalkulačka",
  "mapa","město","vesnice","ulice","náměstí","obchod","trh","škola","kino","muzeum",
  "knihovna","restaurace","café","kostel","parkoviště","zahrada","pláž","přístav","letiště","vlak",
  "autobus","tramvaj","taxi","motorka","lod","kufr","batoh","zavazadlo","pas","vstupenka",
  "peníze","bankomat","karta","účtenka","sleva","cena","obchodník","pokladna","dárky","narozeniny",
  "oslava","svatba","film","seriál","herec","herečka","režisér","scéna","dialog","hudebník",
  "zpěvák","kytara","bicí","piano","klavír","orkestr","koncert","festival","umění","malíř",
  "socha","obrazy","galerie","výstava","škola","učebna","laboratoř","cvičení","dějepis","matematika",
  "fyzika","chemie","biologie","geografie","jazyk","čeština","angličtina","dějepis","hudebka","výtvarná výchova",
  "hodina","zvonění"," přestávka","oběd","svačina","školník","ředitel","žákyně","student","studium",
  "projekt","úspěch","soutěž","cena","medaile","trofej","trenér","tým","fanoušek","střídat",
  "zápasník","hřiště","branka","gól","vítězství","porážka","remíza","trénink","rychlost","síla",
  "vytrvalost","pravidla","rozhodčí","strategie","plánování","šikovnost","obratnost","taktika","postřeh","reflex",
  "zbraně","obrana","útok","míč","lano","síť","brankář","útočník","obránce","střelec",
  "věda","laboratoř","experiment","výzkum","teorie","hypotéza","výsledek","pozorování","vzorek","chemikálie",
  "mikroskop","dalekohled","satelit","robotika","programování","kód","algoritmus","počítač","aplikace","hra",
  "web","server","databáze","uživatel","heslo","účet","profil","komentář","sdílení","fotografie",
  "sociální síť","blog","zpráva","noviny","časopis","článek","rozhovor","reportáž","sport","zprávy",
  "počasí","teplota","vlhkost","mrak","bouřka","blesk","hrom","déšť","sníh","kroupy",
  "mráz","led","náledí","zimní","letní","jarní","podzimní","sezóna","prší","slunečno",
  "polooblačno","vítr","bouřka","ticho","hluk","hudba","melodie","rytmus","basa","kytara",
  "zpěv","hlas","řeč","dialog","monolog","herectví","scéna","divadlo","pódium","režie",
  "kamera","záběr","klapka","stříhání","efekt","kostým","maskérna","kulisy","publikum","aplaus",
  "humor","vtip","legrace","úsměv","smích","zábava","party","večírek","párty","hospoda",
  "restaurace","jídelna","kuchyně","vaření","recept","ingredience","mixér","nůž","pánev","hrnec",
  "trouba","gril","pečení","smažení","vaření","dušení","omáčka","koření","pepř","sůl",
  "palačinka","omeleta","salát","sendvič","hamburger","pizza","sůl","cukr","med","ovoce",
  "zelenina","salát","okurka","rajče","cibule","česnek","mrkev","hlávka","brambor","batát",
  "petržel","kopr","bazalka","majoránka","tymián","rozmarýn","oregano","chilli","pepř","sůl",
  "pití","voda","minerálka","limonáda","džus","koláč","zmrzlina","sorbet","čokoláda","čokoláda",
  "bonbón","sladkost","slané","chipsy","sůl","pečené","restaurace","menu","bufet","kavárna",
  "barista","cukrárna","pečivo","rohlík","houska","bageta","sandwich","sýr","máslo","máslový",
  "knedlík","guláš","řízek","polévka","bramboračka","zelňačka","svíčková","omáčka","knedlíky","řízky",
  "ryba","smažený","pečený","grilovaný","kapr","losos","tuňák","makrela","plody moře","krab",
  "krevety","mušle","pstruh","sushi","rýže","soba","udon","pad thai","curry","hladová",
  "chutná","ostra","sladká","slaný","kyselý","hořký","pálivý","studený","teplý","horký",
  "ledový","mražený","čerstvý","sušený","nakládaný","uzený","čerstvost","vůně","zápach","páchnoucí",
  "čistý","špinavý","pořádek","nepořádek","úklid","vysávání","mopping","stírání","utírání","žehlení",
  "praní","pračka","sušička","prášek","aviváž","žehlička","věšení","koš","háček","skříň",
  "police","šuplík","stolní","židle","křeslo","gauč","pohovka","koberec","závěs","žaluzi",
  "lumbar","střecha","okap","okno","sklo","dveře","klika","zámek","pokus","pokoj",
  "ložnice","kuchyně","koupelna","toaleta","garáž","sklep","terasa","balkon","schody","výťah",
  "vchod","chodba","vstup","schránka","pošta","poštovní","balík","zásilka","doručení","adresát",
  "dopis","pohled","známka","poštovní schránka","list","papír","tužka","fix","zápisník","blok",
  "pero","propiska","pastelka","křída","tabule","flipchart","prezentace","prezentační","mikrofon","reproduktor",
  "zásuvka","kabel","nabíječka","baterie","zásuvka","adaptér","hlasitost","ticho","hluk","klid",
  "relax","odpočinek","spaní","polštář","deka","peřina","postel","matrace","ráno","budík",
  "snídaně","večeře","oběd","svačina","pauza","doba","minuta","hodina","týden","měsíc",
  "rok","století","doba","věk","čas","časopis","kalendar","datum","svátek","nový rok",
  "vánoce","velikonoce","svátek práce","den matek","den otců","rodiče","rodina","přítel","kamarád","známý",
  "spolužák","spolupracovník","kolega","šéf","vedoucí","zaměstnání","brigáda","profese","povolání","lékař",
  "zubař","lékařka","učitel","programátor","kuchař","servírka","pokojská","řidič","automechanik","kadeřník",
  "kosmetička","prodejce","pokladní","umělec","malíř","fotograf","grafik","designér","architekt","stavbař",
  "zedník","elektrikář","instalatér","truhlář","kutil","domov","bydlení","pronájem","hypotéka","nájem",
  "smlouva","dokument","doklad","osobní","průkaz","řidičák","OP","pas","rodný list","práce",
  "studie","univerzita","fakulta","katedra","seminář","kurz","certifikát","diplom","práce","úspěch",
  "čest","povýšení","placení","banky","účet","spoření","investice","fond","burza","akcie",
  "měna","euro","koruna","dolary","platba","převod","výběr","vklad","úrok","sazba",
  "smlouva","pojistka","pojištění","škoda","nárok","ošetření","léčba","nemoc","bolest","teplota",
  "záloha","rehabilitace","doktor","sestra","medikament","lék","tableta","sirup","vakcína","očkování",
  "nemocnice","ordinace","klinika","ligament","kost","sval","svalstvo","tělo","hlava","oko",
  "ucho","nos","ústa","jazyk","zub","zuby","srdce","plíce","játra","žaludek",
  "mozek","kůže","vlasy","nehet","ruky","nohy","paže","rameno","koleno","kotník",
  "břišní","hrudní","záda","páteř","krev","žilní","tepna","teplota","puls","tlak",
  "sportovci","atleti","závody","maraton","půlmaraton","sprint","vrh","hod","skok","ocenění",
  "trénink","výzva","cíl","motivace","síla","rychlost","vytrvalost","zotavení","rehab","masáž",
  "zdraví","výživa","vitamín","minerál","protein","sacharid","tuk","kalorie","strava","dieta",
  "záliba","koníček","sbírání","hra","kreslení","čtení","psaní","fotografování","běhání","cyklistika",
  "vaření","pečení","zahradničení","pěstování","rybaření","kempování","turistika","cestování","výlety","výlet",
  "dovolená","hotel","kemp","stany","karavan","mapa","kompas","batoh","spacák","žárovka",
  "oheň","gril","vařič","vařička","nádobí","lžíce","vidlička","nůž","talíř","sklenice",
  "hrnek","termoska","lahev","obal","jednorázové","ubrousek","ručník","toaleta","hygiena","mýdlo",
  "šampon","kartáček","zubní pasta","hřeben","fén","lak","odličovač","krém","krém na ruce","opalovací krém",
  "sluneční brýle","klobouk","deštník","plavky","ručník na pláž","písek","voda","bazén","vlny","surfování",
  "koupání","potápění","masky","foukačka","ploutve","záchrana","záchranný","rychlostní","sbor","záchranář",
  "policie","hasiči","lékaři","zdravotníci","ambulance","siréna","poplach","incident","nehoda","oprava",
  "nástroj","klíč","šroubovák","kleště","pila","kladivo","hřebík","šroub","matice","vrtačka",
  "lepidlo","páska","olej","mazání","údržba","servis","diagnostika","oprava","náhradní díl","výbava",
  "bezpečnost","ochrana","brýle ochranné","rukavice ochranné","helma","vestá","zabezpečení","kamera","alarm","uzávěr",
  "právě","hned","pozítří","zítra","dnes","včera","minulý","příští","časový","termín",
  "schůzka","událost","akce","program","harmonogram","rozvrh","seznam","úkol","todo","hotovo",
  "nedokončeno","priorita","důležité","urgentní","lokace","místo","adresa","GPS","souřadnice","mapa",
  "orientace","směr","sever","jih","východ","západ","rovina","kopec","údolí","příkop",
  "most","tunel","silnice","cesta","chodník","cyklostezka","přechod","značka","stopka","semafor",
  "světlo","zelené","červené","žluté","bliká","průjezd","zastávka","nádraží","stanice","terminál",
  "trajekt","most","přejezd","přístav","plán","itinerář","cesta","trasa","odjezd","příjezd",
  "odlet","přílet","zpoždění","zmeškání","rezervace","rezervovat","rezervace míst","pokladna","check-in","bording",
  "pas","vízum","celní","kontrola","bezpečnostní kontrola","zavazadlo","kufr","příruční","přepravní","hmotnost",
  "limit","poplatek","daně","celní poplatek","pojištění","záruka","reklamace","vrácení","garance","záruka",
  "fakturace","faktura","účetnictví","platba","záloha","vrátka","dárek","překvapení","balení","krabička",
  "stužka","papír","ozdoba","vánek","svíčka","lampa","světlo","žárovka","svícen","stolek",
  "žaluzie","rolety","zahrádka","květináč","trávník","sekačka","zahradník","sad","vinice","pole",
  "obilí","pšenice","žito","ječmen","rýže pole","bramborové pole","zeleninová zahrada","skleníky","růžový keř","jabloň",
  "slivon","hruška strom","třešeň","borovice","smrk","modřín","listí","jehličí","kůra","kořen",
  "květ","plod","semínko","víno","pivo","vínečko","destilát","limonáda","koktejl","smoothie",
  "cukr","cukrovinky","čokoládový","čokolada","lanýže","bonbón","sušenka","keks","pečivo","bageta",
  "croissant","sendvič","hambáč","hotdog","bramborák","palačinka","lívance","knedlík","guláš","polévka",
  "vývar","smažený sýr","řízek","hamburger","středa","pondělí","úterý","čtvrtek","pátek","sobota",
  "neděle","víkend","prázdniny","letní tábory","přátelství","romantika","vztah","randění","rande","polibek",
  "přátelé","kamarádství","parta","společnost","klub","kroužek","sportovní kroužek","divadlo kroužek","film klub","čtenářský",
  "herní klan","tým","spolupráce","soupeření","žert","rozhovor","telefonát","sms","email","pošta",
  "balík","pozvánka","vstupenka","voucher","dárkový","coupon","sleva","výprodej","akcni","kupón",
  "katalog","brožura","leták","plakát","reklama","inzerát","kampaň","propagace","sponzor","partner",
  "sponzoring","dar","darování","charita","sbírka","pomoc","dobrovolník","organizace","spolek","sdružení",
  "projekt","účel","cíl","mise","týmová práce","vedení","koordinace","plánování","monitoring","vyhodnocení",
  "prehled","statistika","graf","tabulka","škála","měření","testování","kvalita","kontrola","audit",
  "certifikace","standard","norma","pravidlo","řízení","řízení kvality","strategie","vize","mise","hodnota",
  "etika","práce","odměna","plat","mzda","výplata","bonus","smlouva","podmínky","benefity",
  "dovolená","placená","neplacená","práce z domova","home office","flexibilita","směny","noční","denní","pracovní doba",
  "školení","kurzy","workshop","seminar","konference","setkání","networking","kontakt","vizitka","profil",
  "životopis","CV","motivační dopis","přijímací","interview","rozhovor","zkouška","test","assessment","hodnocení",
  "zpětná vazba","pochvala","kritika","motivace","odměna","pokuta","sankce","řešení","konflikt","mediace",
  "komunikace","mluvení","poslouchání","argument","diskuse","debata","hlasování","rozhodnutí","návrh","hlas",
  "rada","tip","nápad","inovace","změna","zlepšení","optimalizace","upgrade","aktualizace","verze",
  "soubor","dokument","složka","adresář","kopie","záloha","export","import","synchronizace","sdílení",
  "práva","přístup","role","admin","moderátor","uživatel","host","člen","registrovaný","anonimní",
  "profil","nastavení","preference","tema","barva","font","velikost","rozvržení","design","ui",
  "ux","testování","spustit","debug","chyba","bug","oprava","patch","release","deploy",
  "server","hosting","doména","SSL","https","http","api","endpoint","request","response",
  "status","kód","200","404","500","timeout","chyba sítě","konektivita","latence","rychlost",
  "cache","paměť","disk","cpu","procesor","grafika","gpu","monitor","obrazovka","rozlišení",
  "klávesnice","myš","touchpad","kamera","mikrofon","reproduktor","sluchátka","světlo","stůl","židle",
  "ergonomie","komfort","zdraví","pohoda","spánek","jídlo","pití","přestávka","procházka","venku",
  "příroda","výhled","hory","údolí","moře","oceán","pláž","skála","jeskyně","řeka",
  "tok","vodopád","pramen","jezero","rybník","břeh","přístav","maják","poloostrov","záliv",
  "zima","léto","jaro","podzim","listí","květ","plod","úroda","sklizeň","období",
  "smesa","snídaně","brunch","večere","přejídání","zdravě","fit","posilovna","cvik","série",
  "opakování","pauza","rozcvička","strečink","zahřátí","vyrovnání","postoj","technika","správná","chybná"
];

async function runSeed() {
  console.log('Seeding words:', words.length);
  for (let i = 0; i < words.length; i += 100) {
    const chunk = words.slice(i, i + 100).map((t) => ({ text: t }));
    const { error } = await supabaseServer.from('words').insert(chunk);
    if (error) {
      console.error('Chyba při vkládání chunku:', error);
      return;
    }
    console.log(`Inserted ${i + chunk.length}/${words.length}`);
  }
  console.log('Hotovo.');
}

runSeed().catch(console.error);
